services:
  authorization-database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authorization-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local_app -d authorization-db" ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 10s
  authorization-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_LINK=jdbc:postgresql://authorization-database:5432/authorization-db?sslmode=disable
      - MAIL_USERNAME=$MAIL_USERNAME
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - MAILGUN_URL=${MAILGUN_URL:-http://localhost:8079}
      - MAILGUN_USERNAME=${MAILGUN_USERNAME:-api}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-token}
    depends_on:
      authorization-database:
        condition: service_healthy