eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    renewal-percent-threshold: 0.49
server:
  port: ${PORT:8761}
spring:
  application:
    name: discovery-service
management:
  endpoints:
    web:
      cors:
        allowed-origins: ${FRONTEND_URL:http://localhost:5173}
        allowed-methods: "GET"
        allowed-headers: "*"
        exposed-headers: "Access-Control-Allow-Origin,Access-Control-Allow-Credentials"
