services:
  task-database:
    image: "postgres:latest"
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: local_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task-db
      PGPORT: 5434
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local_app -d task-db" ]
      interval: 10s
      retries: 10
      start_period: 20s
      timeout: 10s
  task-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=$SPRING_PROFILES_ACTIVE
      - TASK_POSTGRES_LINK=jdbc:postgresql://task-database:5434/task-db?sslmode=disable
    depends_on:
      task-database:
        condition: service_healthy