name: Discovery Service Deploy
on:
  workflow_run:
    workflows:
      - UI Tests Pipeline
    types:
      - completed
    secrets: inherit
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  discovery-changes:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push'
    outputs:
      discovery: ${{ steps.filter.outputs.rerun_required }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check changes in Discovery Service
        uses: ./.github/actions/rerun-required
        id: filter
        with:
          token: ${{ secrets.MAXQ_ACTION_PAT }}
          files: 'backend/discovery-service/**'
          artifact-name: discovery-service-jar
          artifact-path: backend/discovery-service/build/libs

  discovery-service-deploy:
    needs: discovery-changes
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.event == 'push' &&
      needs.discovery-changes.outputs.discovery == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: ./.github/actions/download-artifact
        with:
          artifact_name: discovery-service-jar
          path: backend/discovery-service/build/libs
          github_token: ${{ github.token }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./backend/discovery-service
          file: ./backend/discovery-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/discovery-service:1.0.0
            ${{ secrets.DOCKER_USERNAME }}/discovery-service:latest
          labels: discovery-service

      - name: Deploy to Render
        run: |
          curl ${{ secrets.DISCOVERY_RENDER_HOOK }}

      - name: Wait for application to be ready
        uses: './.github/actions/health-check'
        with:
          timeout_minutes: 10
          url: ${{ secrets.DISCOVERY_API_URL }}/actuator/health